### ISSUE TITLE
How to Mock different request with different jsons

### ISSUE THREAD

**Issue by e4basil** [speekha/httpmocker#33]
How to Mock different requests with different jsons

**Comment by speekha** [comment]
Could you explain your problem a bit more?
As stated in the readme file (as well as the blog post), you need to create a JSON file in the proper folder (depending on the File Policy you use. By default, your JSON path should match the URL path). So different requests for different URL should have different files. If you're talking about requests on the same URL but with different parameters or headers for instance, then all the responses should be in the same JSON file. Have a look at the demo app in the repository or the tests in the tests folder for some examples.

**Comment by speekha** [comment]
Maybe the easiest way to see how the Json config files work is to set your interceptor on record and look at the result.

**Comment by e4basil** [comment]
ok i got it

**Comment by e4basil** [comment]
is any option to mock particular APIs only and fetch others from the server?

**Comment by speekha** [comment]
Use the "mixed mode": if a mock file is found, it will be used, if not,  the server call will go through.

**Comment by e4basil** [comment]
how can i use the "mixed mode", can you give me demo code

**Comment by speekha** [comment]
Call setInterceptorStatus(MIXED) in your builder when you're setting the interceptor up. Or you can also change the mode afterwards: interceptor.mode = RECORD

**Comment by speekha** [comment]
I'm assuming your issue has been answered and will close it. Let me know if you need more help using the lib or if I can improve its documentation to make its use more straightforward.
