### ISSUE TITLE
Record mode issue?

### ISSUE THREAD

**Issue by cpeppas** [speekha/httpmocker#43]
I am using the following builder setup to just to record some canned responses in a directory.

```
 MockResponseInterceptor.Builder()
            .parseScenariosWith(GsonMapper())
            .loadFileWith { context.assets.open(it) }
            .setInterceptorStatus(MockResponseInterceptor.Mode.RECORD)
            .saveScenariosIn(File(Environment.getExternalStoragePublicDirectory(
                    Environment.DIRECTORY_DOWNLOADS).absolutePath))
.saveScenariosIn(File(Environment.getExternalStorageDirectory().path))
            .build()
```

I also tried File(Environment.getExternalStorageDirectory().path) without any luck

I cannot see any json respons saved or any logs indicating a issue.
Am I missing something?

**Comment by speekha** [comment]
Did you add the writing storage permission to your app (and ask for it at runtime if you're on Android > 5) ? If you add the Android connector for SLF4J, you should be able to check the logs in your console and find an error explaining why it's not recording.

**Comment by cpeppas** [comment]
@speekha thanks for the immediate response!. There is no issue. it was me using an API 26 without asking user for permission. Closing this.

**Comment by speekha** [comment]
@cpeppas I always forget it at first too! ;-)
