### ISSUE TITLE
Allow custom RequestDescriptor.match(request: Request) handler

### ISSUE THREAD

**Issue by C2H6O** [speekha/httpmocker#44]
I have 2 requests hitting the same endpoint that differ in several ways:

The first request has no params (since Retrofit strips out `null` param values):
```
"request": {
      "method": "GET",
      "headers": {},
      "params": {}
    }
```

The second request does have a param:
```
"request": {
      "method": "GET",
      "headers": {},
      "params": {
        "token": "eyJvYmplY3Rfc2VxIjo2NDUyNTd9"
      }
    }
```

The problem is that the matcher always matches the first request, since `params.all { request.url().queryParameter(it.key) == it.value }` short-circuits and always returns true for a request that has empty `params` list.

Adding `params.size == request.url().querySize()` check to the `RequestDescriptor.match(request: Request)` fixes the issue, but I'm not sure if that's the desired behavior in every case and/or for this library in general.

**Comment by speekha** [comment]
Just swap your two requests around: start your mock file with the more restrictive one (the one with the token), then put the empty one second. This way, when you call that request with the token, it will match the first declared request and stop there. When you call the second one (without parameters), it will try the first possibility, then move on to the second one.

**Comment by speekha** [comment]
Your fix would imply that you want an exact match on query parameter, which would imply you always have to declare all parameters, and can't choose to ignore certain ones. But I guess I could add the possibility for an exact match for certain requests if needed.

**Comment by speekha** [comment]
I'm assuming your question has been answered, and will close the issue. Let me know if you have any more questions.
