### ISSUE TITLE
Ability to execute the chain with a new request in Mixed mode.

### ISSUE THREAD

**Issue by jyotid** [speekha/httpmocker#91]
Currently, the Interceptor used in my project appends some extra headers and tokens depending on certain conditions.
<img width="622" alt="Screenshot 2020-04-19 at 2 58 31 PM" src="https://user-images.githubusercontent.com/19976020/79684365-4b438e80-824e-11ea-89af-70707dcc3a56.png">

Now if I were to change my above function as 
<img width="772" alt="Screenshot 2020-04-19 at 2 59 39 PM" src="https://user-images.githubusercontent.com/19976020/79684377-6c0be400-824e-11ea-83d3-56e30dddfb18.png">

In mixed mode the api(which are not going to give the mock data) will never be able to run with "extra_header". CMIIW.

**Comment by speekha** [comment]
Hi. I'm not sure I understand what you're trying to do here. Are you trying to add some extra headers on mocked requests but not on actual requests? I think I would need a bit more details to help.

**Comment by jyotid** [comment]
Hey, we are adding extra headers to the actual request, which can be easily bypassed in case of mocked requests. But in the case of mixed mode(which handles both actual and mocked), there is no way to add these extra headers.

**Comment by speekha** [comment]
Hi.
Sorry for taking so long to get back to you. I'm not sure how to help here. The whole point of HttpMocker is to abstract away the fact that your network requests are real or mocked. My take is that both mocked requests and real ones should have the same headers. Just treat all of your requests as if they were real ones.
I fail to see why those headers would be problematic with mocked responses. Given that you decide what is important or not when you match requests, can't you just simply ignore those headers in mocked requests?

**Comment by speekha** [comment]
No new information in the last 4 months. Issue will be closed.
